// Code generated by protoc-gen-go. DO NOT EDIT.
// source: awscred.proto

package awscred

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetOnRequest struct {
	Profile              string   `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOnRequest) Reset()         { *m = SetOnRequest{} }
func (m *SetOnRequest) String() string { return proto.CompactTextString(m) }
func (*SetOnRequest) ProtoMessage()    {}
func (*SetOnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94e10cbc5c16adca, []int{0}
}

func (m *SetOnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOnRequest.Unmarshal(m, b)
}
func (m *SetOnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOnRequest.Marshal(b, m, deterministic)
}
func (m *SetOnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOnRequest.Merge(m, src)
}
func (m *SetOnRequest) XXX_Size() int {
	return xxx_messageInfo_SetOnRequest.Size(m)
}
func (m *SetOnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetOnRequest proto.InternalMessageInfo

func (m *SetOnRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

type SetOnResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOnResponse) Reset()         { *m = SetOnResponse{} }
func (m *SetOnResponse) String() string { return proto.CompactTextString(m) }
func (*SetOnResponse) ProtoMessage()    {}
func (*SetOnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94e10cbc5c16adca, []int{1}
}

func (m *SetOnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOnResponse.Unmarshal(m, b)
}
func (m *SetOnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOnResponse.Marshal(b, m, deterministic)
}
func (m *SetOnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOnResponse.Merge(m, src)
}
func (m *SetOnResponse) XXX_Size() int {
	return xxx_messageInfo_SetOnResponse.Size(m)
}
func (m *SetOnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetOnResponse proto.InternalMessageInfo

func (m *SetOnResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SetOffRequest struct {
	Profile              string   `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOffRequest) Reset()         { *m = SetOffRequest{} }
func (m *SetOffRequest) String() string { return proto.CompactTextString(m) }
func (*SetOffRequest) ProtoMessage()    {}
func (*SetOffRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94e10cbc5c16adca, []int{2}
}

func (m *SetOffRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOffRequest.Unmarshal(m, b)
}
func (m *SetOffRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOffRequest.Marshal(b, m, deterministic)
}
func (m *SetOffRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOffRequest.Merge(m, src)
}
func (m *SetOffRequest) XXX_Size() int {
	return xxx_messageInfo_SetOffRequest.Size(m)
}
func (m *SetOffRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOffRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetOffRequest proto.InternalMessageInfo

func (m *SetOffRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

type SetOffResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOffResponse) Reset()         { *m = SetOffResponse{} }
func (m *SetOffResponse) String() string { return proto.CompactTextString(m) }
func (*SetOffResponse) ProtoMessage()    {}
func (*SetOffResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94e10cbc5c16adca, []int{3}
}

func (m *SetOffResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOffResponse.Unmarshal(m, b)
}
func (m *SetOffResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOffResponse.Marshal(b, m, deterministic)
}
func (m *SetOffResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOffResponse.Merge(m, src)
}
func (m *SetOffResponse) XXX_Size() int {
	return xxx_messageInfo_SetOffResponse.Size(m)
}
func (m *SetOffResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOffResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetOffResponse proto.InternalMessageInfo

func (m *SetOffResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SetConfigRequest struct {
	Profile              string   `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Serial               string   `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Duration             int64    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94e10cbc5c16adca, []int{4}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *SetConfigRequest) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *SetConfigRequest) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type SetConfigResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94e10cbc5c16adca, []int{5}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

func (m *SetConfigResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SetGenerateRequest struct {
	Profile              string   `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGenerateRequest) Reset()         { *m = SetGenerateRequest{} }
func (m *SetGenerateRequest) String() string { return proto.CompactTextString(m) }
func (*SetGenerateRequest) ProtoMessage()    {}
func (*SetGenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94e10cbc5c16adca, []int{6}
}

func (m *SetGenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGenerateRequest.Unmarshal(m, b)
}
func (m *SetGenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGenerateRequest.Marshal(b, m, deterministic)
}
func (m *SetGenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGenerateRequest.Merge(m, src)
}
func (m *SetGenerateRequest) XXX_Size() int {
	return xxx_messageInfo_SetGenerateRequest.Size(m)
}
func (m *SetGenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetGenerateRequest proto.InternalMessageInfo

func (m *SetGenerateRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *SetGenerateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SetGenerateResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGenerateResponse) Reset()         { *m = SetGenerateResponse{} }
func (m *SetGenerateResponse) String() string { return proto.CompactTextString(m) }
func (*SetGenerateResponse) ProtoMessage()    {}
func (*SetGenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94e10cbc5c16adca, []int{7}
}

func (m *SetGenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGenerateResponse.Unmarshal(m, b)
}
func (m *SetGenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGenerateResponse.Marshal(b, m, deterministic)
}
func (m *SetGenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGenerateResponse.Merge(m, src)
}
func (m *SetGenerateResponse) XXX_Size() int {
	return xxx_messageInfo_SetGenerateResponse.Size(m)
}
func (m *SetGenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetGenerateResponse proto.InternalMessageInfo

func (m *SetGenerateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetProfileListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileListRequest) Reset()         { *m = GetProfileListRequest{} }
func (m *GetProfileListRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileListRequest) ProtoMessage()    {}
func (*GetProfileListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94e10cbc5c16adca, []int{8}
}

func (m *GetProfileListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileListRequest.Unmarshal(m, b)
}
func (m *GetProfileListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileListRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileListRequest.Merge(m, src)
}
func (m *GetProfileListRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileListRequest.Size(m)
}
func (m *GetProfileListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileListRequest proto.InternalMessageInfo

type GetProfileListResponse struct {
	Profiles             []*Profile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	ErrorMessage         string     `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProfileListResponse) Reset()         { *m = GetProfileListResponse{} }
func (m *GetProfileListResponse) String() string { return proto.CompactTextString(m) }
func (*GetProfileListResponse) ProtoMessage()    {}
func (*GetProfileListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94e10cbc5c16adca, []int{9}
}

func (m *GetProfileListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileListResponse.Unmarshal(m, b)
}
func (m *GetProfileListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileListResponse.Marshal(b, m, deterministic)
}
func (m *GetProfileListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileListResponse.Merge(m, src)
}
func (m *GetProfileListResponse) XXX_Size() int {
	return xxx_messageInfo_GetProfileListResponse.Size(m)
}
func (m *GetProfileListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileListResponse proto.InternalMessageInfo

func (m *GetProfileListResponse) GetProfiles() []*Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func (m *GetProfileListResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type Profile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	On                   bool     `protobuf:"varint,2,opt,name=on,proto3" json:"on,omitempty"`
	Serial               string   `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Duration             int64    `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Expired              string   `protobuf:"bytes,5,opt,name=expired,proto3" json:"expired,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_94e10cbc5c16adca, []int{10}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetOn() bool {
	if m != nil {
		return m.On
	}
	return false
}

func (m *Profile) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Profile) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Profile) GetExpired() string {
	if m != nil {
		return m.Expired
	}
	return ""
}

func init() {
	proto.RegisterType((*SetOnRequest)(nil), "awscred.SetOnRequest")
	proto.RegisterType((*SetOnResponse)(nil), "awscred.SetOnResponse")
	proto.RegisterType((*SetOffRequest)(nil), "awscred.SetOffRequest")
	proto.RegisterType((*SetOffResponse)(nil), "awscred.SetOffResponse")
	proto.RegisterType((*SetConfigRequest)(nil), "awscred.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "awscred.SetConfigResponse")
	proto.RegisterType((*SetGenerateRequest)(nil), "awscred.SetGenerateRequest")
	proto.RegisterType((*SetGenerateResponse)(nil), "awscred.SetGenerateResponse")
	proto.RegisterType((*GetProfileListRequest)(nil), "awscred.GetProfileListRequest")
	proto.RegisterType((*GetProfileListResponse)(nil), "awscred.GetProfileListResponse")
	proto.RegisterType((*Profile)(nil), "awscred.Profile")
}

func init() { proto.RegisterFile("awscred.proto", fileDescriptor_94e10cbc5c16adca) }

var fileDescriptor_94e10cbc5c16adca = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4f, 0xef, 0x93, 0x40,
	0x10, 0x0d, 0xd0, 0x96, 0x76, 0xfa, 0x27, 0x75, 0xb5, 0x2d, 0xa2, 0xd1, 0x86, 0x13, 0x1a, 0xad,
	0x49, 0x4d, 0x4c, 0x3c, 0x6a, 0x4d, 0xea, 0x41, 0xa3, 0xc2, 0xc1, 0xab, 0x28, 0x43, 0x83, 0xb6,
	0xbb, 0xb8, 0xbb, 0x8d, 0x26, 0x7e, 0x56, 0xbf, 0xcb, 0x2f, 0x85, 0x81, 0x40, 0x7f, 0x6d, 0xb8,
	0xf1, 0x76, 0xde, 0xbe, 0x79, 0x3b, 0xf3, 0x02, 0x8c, 0xa3, 0x3f, 0xea, 0x87, 0xc4, 0x78, 0x95,
	0x49, 0xa1, 0x05, 0xb3, 0x09, 0x7a, 0x3e, 0x8c, 0x42, 0xd4, 0x9f, 0x78, 0x80, 0xbf, 0x8f, 0xa8,
	0x34, 0x73, 0xc0, 0xce, 0xa4, 0x48, 0xd2, 0x3d, 0x3a, 0xc6, 0xd2, 0xf0, 0x07, 0x41, 0x09, 0xbd,
	0x27, 0x30, 0x26, 0xa6, 0xca, 0x04, 0x57, 0x78, 0xa2, 0x1e, 0x50, 0xa9, 0x68, 0x57, 0x51, 0x09,
	0x96, 0xd4, 0x24, 0x69, 0x57, 0x7d, 0x0a, 0x93, 0x92, 0xda, 0x2a, 0xfb, 0x0d, 0xa6, 0x21, 0xea,
	0x8d, 0xe0, 0x49, 0xba, 0x6b, 0x55, 0x66, 0x73, 0xe8, 0x29, 0x94, 0x69, 0xb4, 0x77, 0xcc, 0xbc,
	0x40, 0x88, 0xb9, 0xd0, 0x8f, 0x8f, 0x32, 0xd2, 0xa9, 0xe0, 0x8e, 0xb5, 0x34, 0x7c, 0x2b, 0xa8,
	0xb0, 0xf7, 0x1c, 0xee, 0xd4, 0x3a, 0xb4, 0x1a, 0x7a, 0x07, 0x2c, 0x44, 0xbd, 0x45, 0x8e, 0x32,
	0xd2, 0xd8, 0x6e, 0xe9, 0x1e, 0x74, 0xb5, 0xf8, 0x85, 0x9c, 0x1c, 0x15, 0xc0, 0x7b, 0x01, 0x77,
	0x1b, 0x2a, 0xad, 0x6d, 0x17, 0x30, 0xdb, 0xa2, 0xfe, 0x5c, 0x88, 0x7e, 0x48, 0x95, 0xa6, 0xce,
	0xde, 0x4f, 0x98, 0x9f, 0x17, 0x48, 0xec, 0x19, 0xf4, 0xc9, 0x84, 0x72, 0x8c, 0xa5, 0xe5, 0x0f,
	0xd7, 0xd3, 0x55, 0x99, 0x08, 0xe2, 0x07, 0x15, 0x83, 0x79, 0x30, 0x42, 0x29, 0x85, 0xfc, 0x48,
	0xfd, 0x0b, 0xbb, 0x8d, 0x33, 0xef, 0x1f, 0xd8, 0x74, 0x91, 0x31, 0xe8, 0xf0, 0xe8, 0x50, 0xda,
	0xcc, 0xbf, 0xd9, 0x04, 0x4c, 0x51, 0xbc, 0xb3, 0x1f, 0x98, 0x82, 0xd7, 0xb6, 0x61, 0x5d, 0xdd,
	0x46, 0xa7, 0xb9, 0x8d, 0xd3, 0x04, 0xf0, 0x6f, 0x96, 0x4a, 0x8c, 0x9d, 0x6e, 0x31, 0x01, 0x82,
	0xeb, 0xff, 0x26, 0xd8, 0x6f, 0xbe, 0x86, 0x1b, 0x89, 0x31, 0x7b, 0x05, 0xdd, 0x3c, 0x97, 0x6c,
	0x56, 0xbd, 0xa8, 0x9e, 0x68, 0x77, 0x7e, 0x7e, 0x4c, 0x23, 0x79, 0x0d, 0xbd, 0x22, 0x79, 0xac,
	0xc9, 0xa8, 0x52, 0xeb, 0x2e, 0x6e, 0x9d, 0xd3, 0xd5, 0xb7, 0x30, 0xa8, 0x62, 0xc2, 0xee, 0xd7,
	0x59, 0x8d, 0x70, 0xba, 0xee, 0xa5, 0x12, 0x69, 0xbc, 0x87, 0x61, 0x6d, 0xeb, 0xec, 0x41, 0x9d,
	0x7a, 0x96, 0x28, 0xf7, 0xe1, 0xe5, 0x22, 0x29, 0x7d, 0x81, 0x49, 0x73, 0xeb, 0xec, 0x71, 0xc5,
	0xbf, 0x1c, 0x07, 0xf7, 0xd1, 0x55, 0x42, 0xde, 0xf0, 0x7b, 0x2f, 0xff, 0x4b, 0xbc, 0xbc, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x6d, 0x97, 0x08, 0x0f, 0x36, 0x04, 0x00, 0x00,
}
